// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssowiinfotyifajtmivo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzb3dpaW5mb3R5aWZhanRtaXZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNDk4NjIsImV4cCI6MjA2MzkyNTg2Mn0.9jPgw2eG6La3thIdOQuzVg6sXGXuxTLsLBLjudxwh7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);